carbon-calc/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :responses
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

carbon-calc/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

carbon-calc/app/models/response.rb
class Response < ApplicationRecord
end

carbon-calc/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

carbon-calc/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

carbon-calc/app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
	def new
	end

	def show
    	@response = Response.find(params[:id])
  	end

	def create
		@response = Response.new(params[:reponse])
 
  		@response.save
  		redirect_to @response
	end
	private
		def reponse_params
			params.require(:response).permit(:title, :text)
		end
end

carbon-calc/app/helpers/application_helper.rb
module ApplicationHelper
end

carbon-calc/app/helpers/home_helper.rb
module HomeHelper
end

carbon-calc/app/helpers/responses_helper.rb
module ResponsesHelper
end

carbon-calc/app/views/home/index.html.erb
<h1>Home</h1>
<p>This is the home page of our app</p>

carbon-calc/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarbonCalc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

carbon-calc/app/views/responses/new.html.erb
<h1>Response page</h1>
<%= form_with scope: :response, url: responses_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

carbon-calc/app/views/responses/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @response.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @response.text %>
</p>